### PR TITLE
Adding Barcelona to the js code retreat #2

### PR DESCRIPTION
**Pull request by otorras**

### CODE REVIEW

**Comment by wolframkriesing** [comment]
Hey Oriol, awesome that Barcelona is joining. If you guys need help ping us on twitter

**Comment by nonken** [comment]
woot woot

**Comment by nonken** [comment]
Oh, is something missing, don't see it on http://jscoderetreat.com/2/

**Comment by wolframkriesing** [comment]
now :)
i added it

## 

Kind regards / Saludos / Mit freundlichen Grüßen
Come and practice - http://jscoderetreat.com

Wolfram Kriesing
uxebu

kriesing@uxebu.com, mobile: +49 174 300 4595

**Pull request merged**
