### PR TITLE
Change Lanyrd URL to match Munich event

### PR DESCRIPTION
**Pull request by fhemberger**
Please merge, Lanyrd links don't work at the moment.

### CODE REVIEW

**Comment by fhemberger** [comment]
Yay, thanks! Now everything is finally ready to go.

**Comment by fhemberger** [comment]
Well, I guess it has to be me then. ;) It would be great if you could send me the material needed, I've never done this before.

**Comment by wolframkriesing** [comment]
you have taken part in a coderetreat already? that really helps, if u get
the chance i can only recommend it

## 

Kind regards / Saludos / Mit freundlichen Grüßen
Come and practice - http://jscoderetreat.com

Wolfram Kriesing
uxebu

kriesing@uxebu.com, mobile: +49 174 300 4595

**Comment by fhemberger** [comment]
Not yet, that's the reason we're doing one now. ;)

**Pull request merged**
